apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: url-shortener

type: Opaque

stringData:
  POSTGRES_DB: urlshortener
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres